### ISSUE TITLE
hello world alternative

### ISSUE THREAD

**Issue by waynr** [grubnubble/exercism#1]
https://github.com/grubnubble/exercism/blob/4e6f31eed06583d2e031b66730fd37ee040c53c2/python/hello-world/hello_world.py#L1

This is fine, perfectly pythonic. But since you're doing this to learn more python stuff one suggestion i have for an alternative to inspire some thought about what a function is you could define the hello function using:

```
hello = lambda: "Hello, world!"
```

**Comment by waynr** [comment]
Just to be clear this suggestion is not at all a good alternative, just a thought provoking one. 99 percent of the time it's better to define a function using the `def` keyword.

**Comment by grubnubble** [comment]
thanks!
