### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by spacez320** [grubnubble/exercism#2]
- I always advocate for pydoc conformed documentation, especially at the very least for functions. https://www.python.org/dev/peps/pep-0257/

- I'm always tempted to make simple if/else more succinct. Can you combine the assignments in `Rational.__init__` at the end of the function into a one-line statement?

- I did not know Python had `NaN`! Another method you could have done to handle division by zero is throwing an exception. Have you done that before? Does Python core provide you with one that fits this case?

- Sweet test coverage. How would I report inside the repo, maybe on the README, what the test coverage is?

**Comment by grubnubble** [comment]
2. The only thing I could think of would be
`self.numer = numer if denom > 0 else -numer`
`self.denom = self._abs(denom)`
I feel like I should also handle the case if `denom` is `0` 

3. I could `raise` something, and I thought about doing that. Is it better to raise an error than to return `NaN`? 

4. Exercism gave me the tests :D. The goal was to get the tests to pass, but my personal goal is to get better at Python and learn how to do things more idiomatically.

Thanks!
